stages:
  - build
  - test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_REGISTRY: localhost:5000
  CI_REGISTRY_IMAGE: $DOCKER_REGISTRY/skills/developer-skills-rating-server

default:
  image: docker:23.0.3

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - cache/

build_job:
  stage: build
  only:
    - main
  script:
    - echo "Running build for the server"
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

# disabled
.test_job:
  stage: test
  only:
    - main
  script:
    - echo "Running server tests"
    - docker run --name server-container -d $CI_REGISTRY_IMAGE
    - docker exec server-container npm test --passWithNoTests
    - docker stop server-container
    - docker rm server-container

deploy_job:
  stage: deploy
  only:
    - main
  environment:
    name: development
  script:
    - echo "Deploying to Docker Swarm"
    - |
      docker stack deploy --compose-file docker-compose-dev.yml \
      --with-registry-auth server-skills-stack \
      -c <(envsubst < docker-compose-dev.yml)
