version: '3.8'

services:
  server:
    image: ${CI_REGISTRY_IMAGE}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /app/node_modules
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mongo-data: