version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=dbname
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
