version: '3.8'

services:
  server:
    image: ${CI_REGISTRY_IMAGE}
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=dbname
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mongo-data: